GC included txns based on timestamp
EspressoSystems/hotshot-builder-core pull request #152
Opened 2024-05-22 15:06 UTC by move47

Closes #151

2024-05-22 16:37 UTC, nyospe commented on src/builder_state.rs
> +        // clear the txns from included txns which are older than current timestamp by 3 secs
What? No. I meant, we could clear after... days? Hours, maybe, at the smallest increment.

2024-05-22 18:38 UTC, nyospe commented on src/builder_state.rs
> +        // clear the txns from included txns which are older than current timestamp by 3 secs
We can do 2 hours. But... maybe let's try this instead: https://espresso.zulipchat.com/#narrow/stream/419378-Block-Builder/topic/Staging.20performance.20issues/near/440153803 with the <unit of time> configurable, defaulting to 1 hour.

2024-05-23 18:20 UTC, nyospe requested changes
One purely stylistic request.

Otherwise, looks good.

2024-05-23 18:20 UTC, nyospe commented on src/builder_state.rs
> +
More idiomatic as:

```rust
let (included_txns, included_txns_old, included_txns_expiring, next_txn_garbage_collect_time) = if Instant::now() >= self.next_txn_garbage_collect_time {
            (HashSet::new(), self.included_txns.clone(), self.included_txns_old.clone(), Instant::now() + self.txn_garbage_collect_duration)
} else {
            (self.included_txns.clone(), self.included_txns_old.clone(), self.included_txns_expiring.clone(), self. next_txn_garbage_collect_time)
};
```

2024-05-23 18:27 UTC, move47 commented on src/builder_state.rs
> +
https://github.com/EspressoSystems/hotshot-builder-core/pull/152/commits/bdacf4f49117f5e29163b768077151022eaf7e25

2024-05-23 18:42 UTC, nyospe approved these changes
LGTM

2024-05-23 18:45 UTC, merged